### ISSUE TITLE
Clean up API definitions

### ISSUE THREAD

**Issue by ashkarpetin** [Rebilly/api-definitions#1356]
## Details
- [x] Remove `Common*` Schemas
    - [x]  #1437
    - [x] https://github.com/Rebilly/api-definitions/pull/1438
- [x] Fix discriminator usage
    - [x] https://github.com/Rebilly/api-definitions/pull/1441 from A1Gateway to Ilixium
    - [x] https://github.com/Rebilly/api-definitions/pull/1444 From Ingenico to SafeCharge
    - [x] https://github.com/Rebilly/api-definitions/pull/1446 From SecureTrading to Worldpay
    - [x] ~https://github.com/Rebilly/api-definitions/pull/1447 Misc.~
- [x] Remove excessive schemas reuse
    - ~https://github.com/Rebilly/api-definitions/pull/1476~
    - https://github.com/Rebilly/api-definitions/pull/1499
    - https://github.com/Rebilly/api-definitions/pull/1503
    - https://github.com/Rebilly/api-definitions/pull/1508
    - https://github.com/Rebilly/api-definitions/pull/1511
    - https://github.com/Rebilly/api-definitions/pull/1522
    - https://github.com/Rebilly/api-definitions/pull/1523
    - https://github.com/Rebilly/api-definitions/pull/1525
    - https://github.com/Rebilly/api-definitions/pull/1530
- [x] Flatten the file structure
    - [x] Move schemas referenced from paths to top level directory.
        - https://github.com/Rebilly/api-definitions/pull/1448
        - https://github.com/Rebilly/api-definitions/pull/1450
        - https://github.com/Rebilly/api-definitions/pull/1453
        - https://github.com/Rebilly/api-definitions/pull/1454
        - https://github.com/Rebilly/api-definitions/pull/1455
        - https://github.com/Rebilly/api-definitions/pull/1458
        - https://github.com/Rebilly/api-definitions/pull/1461
        - https://github.com/Rebilly/api-definitions/pull/1462
        - https://github.com/Rebilly/api-definitions/pull/1470
        - https://github.com/Rebilly/api-definitions/pull/1471
        - https://github.com/Rebilly/api-definitions/pull/1473
        - https://github.com/Rebilly/api-definitions/pull/1507
    - [x] Move sub schemas to second level directory.
        - https://github.com/Rebilly/api-definitions/pull/1532
        - https://github.com/Rebilly/api-definitions/pull/1655
        - https://github.com/Rebilly/api-definitions/pull/1659
        - https://github.com/Rebilly/api-definitions/pull/1658
- [ ] ~Update `rebilly-js-sdk` version in FE projects that use TypeScript  and make adjustments to types based on schema changes / removals.~

**Comment by jvc9109** [comment]
Unassigning myself since now I am on cycle work. Once https://github.com/Rebilly/api-definitions/pull/1525 and https://github.com/Rebilly/api-definitions/pull/1530 are merged, the remaining work would be to move everything to first level directory but not `GatewayAccountConfig `.

**Comment by adamaltman** [comment]
Try to complete by Nov 1st
