### ISSUE TITLE
Feature Suggestion: Add "expand" Parameter to refund method

### ISSUE THREAD

**Issue by Anemoiaa** [Rebilly/api-definitions#1821]
We propose adding an "expand" parameter to the refund method. This improvement,  would allow users to specify additional resources to include in the response, reducing the number of requests needed to update information after a transaction refund.

**Example Usage**
`$newTransaction = $coreService->transactions()->refund(id: 1, expand: 'invoices,parentTransaction');
`

**Comment by nevmerzhitsky** [comment]
Will this feature implemented?

**Comment by justnero** [comment]
Hi @Anemoiaa, @nevmerzhitsky! Thank you for the request.
The issue is addressed with https://github.com/Rebilly/rebilly-php/pull/731.
It's available in version 3.1.4 of the SDK.
