### ISSUE TITLE
PHP interfaces of models must declare getEmbedded() method

### ISSUE THREAD

**Issue by nevmerzhitsky** [Rebilly/api-definitions#1896]
Almost all API models have `_embedded` key in responses, therefore all related PHP interfaces of model classes could declare the getter. For some models, only the final model classes define the getter but not the class's interface. This seems incorrect. And this ruins static analyzers like Psalm.

For example, interface `PaymentInstrument` realized by 5 model classes:
- AlternativeInstrument
- BankAccount
- KhelocardCard
- PaymentCard
- PayPalAccount

Each has `public function getEmbedded()`, so the declaration `public function getEmbedded(): ?object` must exist in the interface.

The difference in return types in the case of each model class is not a problem, because PHP fully supports return covariance from PHP 7.4.0.

**Comment by justnero** [comment]
Hi @nevmerzhitsky! Thank you for the request.
The issue is addressed with https://github.com/Rebilly/rebilly-php/pull/733.
It's available in version 3.1.4 of the SDK.
