### ISSUE TITLE
Question - Redoc - "Try it" option

### ISSUE THREAD

**Issue by thim81** [Rebilly/api-definitions#52]
Hi,

I'm looking at your current API documentation, where you are using Redocly. I really like how you organised and customized it. It is very helpful for my own setup.

I wonder how you are able to add and use the "Try It" option?
What configuration option did you use?

Another question is how do you publish the online documentation?
I guess you are using the "redoc-cli" to generate the HMTL page?

Hoping to find some insights from your experience.

Regards,
Tim

**Comment by thim81** [comment]
Another question, how did you get the RedocResponse to work?

`<RedocResponse pointer={"#/components/responses/Unauthorized"} />`

Did you do anything special or included a special packages?

**Comment by adamaltman** [comment]
Hi @thim81 we use Redocly API reference docs. It's a commercial product, and because Redocly spun out of Rebilly, we have an advanced preview version. They will release it later this week, but if you want you can sign up to try it for free at https://app.redoc.ly/signup

**Comment by thim81** [comment]
Hi Adam,

That explains a lot.
I was trying to run the Rebilly API documentation, based on the .redocly.yaml (which is great real example on how to use and customize Redocly), but I had not the same results with the redocly-cli.

It now makes sense why :-)

I signed up, because I'm really curious about the preview of the tools.

Thanks for your helpful response.

Regards,
Tim
